sudo: required
language: java
services:
  - docker
install: true
script:
  - docker build --tag=sdkman/sdkman-cli .
  - docker run --rm -v $PWD:/usr/src/app -v $HOME/.gradle:/root/.gradle sdkman/sdkman-cli clean test --info
after_success:
  - docker run --rm -e BINTRAY_USERNAME=$BINTRAY_USERNAME -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -v $PWD:/usr/src/app -v $HOME/.gradle:/root/.gradle sdkman/sdkman-cli -Penv=production clean assemble bintrayUpload
before_cache:
  - sudo rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: Pj9krGs5nKgyqUB2jlRTA1vuGLgRGlB2ADfbCeqCigiu5BxdJeBRFbsm9Qq95lu503eT/81CvbKUPBCmd/BwNt0ifGzRVNIRqEUZAU3OgRhthc47bu+qUNRli9ZSo5FgLSwaARSElyoy9QJUFfVxIpOUTnq62xlj9fyRh5/BLfY=
  - secure: ooLnOq8QklJgn1A3ymlBJfTRwGn3rpt0sXZTzRf7Tffs+EpfyNkBTAAeOoXdErgHOR5X2erij2t/Eaf5GD9pZnFZbfI9AhfKxzTUyjaW7r3j7QHt/WNyt23EN9cFP7MagFoLCRPr0MJ6NGYnSKpnHFbmN25AilAIPlrpFCquTYE=
